### ISSUE TITLE
support for single end illumina data?

### ISSUE THREAD

**Issue by kapsakcj** [LanLab/ShigEiFinder#3]
Hi - Thanks for developing this wonderful tool. It's been very useful for public health labs analyzing Shigella & E. coli WGS data.

Are there any plans to support single end Illumina data as input for ShigEiFinder? As far as I understand, ShigEiFinder currently supports assemblies and paired end reads as inputs.

Thanks,
Curtis

**Comment by mjohnpayne** [comment]
Hi Curtis,
We can add that I think. I will get back to you once that is set up.
Cheers,
Michael

**Comment by mjohnpayne** [comment]
Hi Curtis,

I have released v1.3.3 on github and will be available on conda soon. There is now a "--single_end" flag that you can add to process single end illumina reads.

Also great to hear the tool has been useful!!

Cheers,
Michael

**Comment by kapsakcj** [comment]
😲 That was fast!!! Thanks so much! You are awesome!

I'll test it out and let you know how it goes

**Comment by mjohnpayne** [comment]
No problems! (1.3.3 is on conda now too)

That would be good thanks :)

**Comment by kapsakcj** [comment]
So far, so good with the new `--single_end` option. I've run 34 various Shigella spp. & E. coli samples through v1.3.3 and all ran flawlessly & produced nearly-identical results to when including their respective R2 files as input.

There were a just a couple of discrepancies, such as the `VIRULENCE_PLASMID` output column differing by 1 (1 gene found in single end vs 2 genes found in paired end for the same sample), but these are to be expected and will vary based on read depth.

I suppose the most important output column is the final `SEROTYPE` column and those did not differ between SE and PE for the same samples.

I very much appreciate that you maintain the recipe on bioconda (another reason that you rock 🙇) but I will mention that for testing I'm using a docker image that I maintain over on [this repo](https://github.com/StaPH-B/docker-builds). A docker image for v1.3.3 will be available on dockerhub & quay.io once we merge this PR https://github.com/StaPH-B/docker-builds/pull/515

Thanks again for adding this new feature! I'll report back if I run into any issues
